### ISSUE TITLE
Missing metadata in full-candidate-subsets.pkl

### ISSUE THREAD

**Issue by noranta4** [Weixin-Liang/MetaShift#1]
Hello, thank you for the nice work and congratulations for the ICLR publication!

I'm playing with the `understanding_full-candidate-subsets-pkl.ipynb` notebook.
Exploring the metadata stored in `full-candidate-subsets.pkl`, some keys seem to be missing.
For instance the ones about attribute contexts:

IN
> ```
> print(VG_node_name_to_img_id['dog(sitting)'])
> print(VG_node_name_to_img_id['dog(jumping)'])
> print(VG_node_name_to_img_id['cat(orange)'])
> print(VG_node_name_to_img_id['cat(white)'])
> ```
OUT
> ```
> set()
> set()
> set()
> set()
> ```

![image](https://user-images.githubusercontent.com/23139217/155280693-ae7a81b9-8261-4a6c-a733-3c9d60ea9771.png)

Other examples: dog(ocean) and dog(street) are missing, dog(grass) is not.

IN
> ```
> print(VG_node_name_to_img_id['dog(ocean)'])
> print(VG_node_name_to_img_id['dog(grass)'])
> print(VG_node_name_to_img_id['dog(street)'])
> ```
OUT
> ```
> set()
> {'2403124', '2386620', '2330800', '2377375', '2395806', '2402433', '2338955', ...
> set()
> ```

![image](https://user-images.githubusercontent.com/23139217/155280748-939d3ee0-a360-45e4-a6bf-2321489dc09e.png)

**Comment by Weixin-Liang** [comment]
Hi, thanks for your interest in our work! 

# General Contexts
For the general contexts, please try
> ```
> print(VG_node_name_to_img_id['ocean(dog)'])
> print(VG_node_name_to_img_id['street(dog)'])
> ```

Some subsets might not be present, since we have a threshold for the minimum number of images within a subset. If interested, one can further utilize the `location` and `weather` fields in the scene graph annotation to construct more subsets. Ref: https://cs.stanford.edu/people/dorarad/gqa/download.html#:~:text=weather

# Attribute Contexts
Good catch! Indeed, the subsets with attribute contexts are stored separately. 
I have updated the repo. Thanks for reporting this issue. 


## Generate the MetaShift-Attributes Dataset (subsets defined by subject attributes)
![image](https://user-images.githubusercontent.com/32794044/155826240-d9b43cff-84e8-4ca8-90b2-1347f0b2c1fc.png)

### Understanding `dataset/attributes_MetaShift/attributes-candidate-subsets.pkl`
`dataset/attributes_MetaShift/attributes-candidate-subsets.pkl` stores the metadata for MetaShift-Attributes, where each subset is defined by the attribute of the subject, e.g. `cat(orange)`, `cat(white)`, `dog(sitting)`, `dog(jumping)`. 

`attributes-candidate-subsets.pkl` has the same data format as `full-candidate-subsets.pkl`. To facilitate understanding, we have provided a notebook `dataset/attributes_MetaShift/understanding_attributes-candidate-subsets-pkl.ipynb` to show how to extract information from it. 

Basically, the pickle file stores a `collections.defaultdict(set)` object, which contains *4,962* keys. Each key is a string of the subset name like `cat(orange)`, and the corresponding value is a list of the IDs of the images that belong to this subset. The image IDs can be used to retrieve the image files from the Visual Genome dataset that you just downloaded. 

### Understanding `dataset/attributes_MetaShift/structured-attributes-candidate-subsets.pkl`
`dataset/attributes_MetaShift/structured-attributes-candidate-subsets.pkl` is very similar to `dataset/attributes_MetaShift/attributes-candidate-subsets.pkl`, but stores the metadata in a more structured way. The pickle file stores a 3-level nested dictionary, with the following structure:

```plain
.
├── key: 'color'
    ├── key: 'cat'              
        ├── key: 'orange'
            ├── value: a list of image IDs
├── key: 'activity'
    ├── key: 'dog'              
        ├── key: 'sitting'
            ├── value: a list of image IDs
        ├── ...
```

See the full attrribute ontology in `ATTRIBUTE_CONTEXT_ONTOLOGY` in `dataset/Constants.py`

```python
ATTRIBUTE_CONTEXT_ONTOLOGY = {
 'darkness': ['dark', 'bright'],
 'dryness': ['wet', 'dry'],
 'colorful': ['colorful', 'shiny'],
 'leaf': ['leafy', 'bare'],
 'emotion': ['happy', 'calm'],
 'sports': ['baseball', 'tennis'],
 'flatness': ['flat', 'curved'],
 'lightness': ['light', 'heavy'],
 'gender': ['male', 'female'],
 'width': ['wide', 'narrow'],
 'depth': ['deep', 'shallow'],
 'hardness': ['hard', 'soft'],
 'cleanliness': ['clean', 'dirty'],
 'switch': ['on', 'off'],
 'thickness': ['thin', 'thick'],
 'openness': ['open', 'closed'],
 'height': ['tall', 'short'],
 'length': ['long', 'short'],
 'fullness': ['full', 'empty'],
 'age': ['young', 'old'],
 'size': ['large', 'small'],
 'pattern': ['checkered', 'striped', 'dress', 'dotted'],
 'shape': ['round', 'rectangular', 'triangular', 'square'],
 'activity': ['waiting', 'staring', 'drinking', 'playing', 'eating', 'cooking', 'resting', 
              'sleeping', 'posing', 'talking', 'looking down', 'looking up', 'driving', 
              'reading', 'brushing teeth', 'flying', 'surfing', 'skiing', 'hanging'],
 'pose': ['walking', 'standing', 'lying', 'sitting', 'running', 'jumping', 'crouching', 
            'bending', 'smiling', 'grazing'],
 'material': ['wood', 'plastic', 'metal', 'glass', 'leather', 'leather', 'porcelain', 
            'concrete', 'paper', 'stone', 'brick'],
 'color': ['white', 'red', 'black', 'green', 'silver', 'gold', 'khaki', 'gray', 
            'dark', 'pink', 'dark blue', 'dark brown',
            'blue', 'yellow', 'tan', 'brown', 'orange', 'purple', 'beige', 'blond', 
            'brunette', 'maroon', 'light blue', 'light brown']
}
```
